iidkId = "1"
iidkPort = "1030"  # "1030"
localHostIp = "172.16.11.102"  # используется для iidk
slave = "VQA-2"
slave_ip = "172.16.11.102"  # используется в тестах
user = "1"
password = "1"
auth = (user, password)  # пользователь/пароль
objId = "999"
dir = "C:\\TEST"
camId = "1"
camName = "test cam"
pci_channel = "1"
personId = "1.999"
departmentId = "1.999"
IdDB = "1"  # id тестовой базы данных, названи таблицы image. В ней должно быть две колонки: image (bytea), tid (integer) в любом порядке, в настройках компа должны быть корректные настройки.
tid = "1"
registrpath = "SOFTWARE\\WOW6432Node\\ISS\\SecurOS\\Niss400\\ImageProcessor"